spring:
  application:
    name: mock-acquirer
  threads:
    virtual:
      enabled: true

server:
  port: ${SERVER_PORT:9090}
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    root: INFO
    com.payflow: INFO
